# %%
#
# Covered transformations (based on the EDA Report — Sections 8.1, 8.2, 8.3):
#   1. Identifier removal — RowNumber, CustomerId, Surname (8.1)
#   2. Imputation          — delegated to the modeling pipeline (stateful — see note) (8.3)
#   3. Binary flags       — HasZeroBalance, HighRiskProducts (8.1)
#   4. Interactions       — AgeInactivity, EngagementScore (8.1)
#   5. Ratios             — BalanceSalaryRatio (8.1)
#   6. Age bins           — AgeGroup (ordinal encoding) (8.1)
#   7. Encoding           — Geography (OHE), Gender (binary), Card Type (OHE) (8.1)
#   8. Selection          — features_to_keep from the EDA Report (8.1)
# ─────────────────────────────────────────────────────────────────────────────

# %%
# Environment setup
import sys
import pandas as pd
from pathlib import Path
import pyarrow.parquet as pq

# Path definitions
ROOT_DIR   = Path(__file__).resolve().parent.parent
CONFIG_DIR = ROOT_DIR / 'config'
PATHS_LIST = [str(ROOT_DIR), str(CONFIG_DIR)]
prep_yaml_path = CONFIG_DIR / 'preprocessing.yaml'

for _p in PATHS_LIST:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from src.utils.logger import get_logger
from src.utils.config_loader import load_yaml

# ── Import all transformers from the src/preprocessing.py module ──────────
from src.preprocessing import (
    DataImputer,
    ColumnDropper,
    BinaryFlagTransformer,
    InteractionFeatureTransformer,
    RatioFeatureTransformer,
    AgeBinTransformer,
    CategoricalEncoder,
    FeatureSelector,
)

# %%
config = load_yaml(CONFIG_DIR / 'pipeline.yaml')
preprocessing = load_yaml(prep_yaml_path)
config.update(preprocessing)  # Merge configs (pipeline + preprocessing)

# Configure logger
log_cfg = config.get('logging')
logger = get_logger(
    name='preprocessamento',
    logging_config=log_cfg
)

logger.info('=== Preprocessing and Feature Engineering — Bank Churn ===')
logger.info('Config loaded: pipeline.yaml + preprocessing.yaml')

# ─────────────────────────────────────────────────────────────────────────────
# Inspect loaded configuration
#
# Teaching point: the student sees exactly what was read from YAML.
# Any change in preprocessing.yaml appears here without changing the code.
# ─────────────────────────────────────────────────────────────────────────────

# %%
prep_cfg    = config.get('preprocessing', {})
output_dir  = ROOT_DIR / prep_cfg.get('output_dir', 'data/features')
output_path = output_dir / prep_cfg.get('output_filename', 'bank_churn_features.parquet')
compression = prep_cfg.get('compression', 'snappy')

logger.info('Output     : %s', output_path)
logger.info('Compression: %s', compression)

# %%
# List configured transformations from YAML
logger.info('Columns to drop         : %d', len(config.get('drop_columns', [])))
logger.info('Binary flags            : %d', len(config.get('binary_flags', [])))
logger.info('Interaction features    : %d', len(config.get('interaction_features', [])))
logger.info('Ratio features          : %d', len(config.get('ratio_features', [])))
logger.info('Categorical encoding    : %d', len(config.get('categorical_encoding', [])))
logger.info('Features for selection  : %d',
            len(config.get('feature_selection', {}).get('features_to_keep', [])))

# %%
# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1 — Dataset Loading
# %%
# Parquet path generated by the ingestion + quality stage
processed_dir = ROOT_DIR / config['paths']['processed_data_dir']
parquet_path  = processed_dir / config['paths']['output_filename']

logger.info('Reading: %s', parquet_path)

if not parquet_path.exists():
    raise FileNotFoundError(
        f"Parquet file not found: {parquet_path}\n"
        "Run ingestao.py and qualidade.py before this script."
    )

# %%
# Inspect schema without loading data (metadata read is cheap)
schema = pq.read_schema(str(parquet_path))
logger.info('Original schema (%d columns):', len(schema))
for field in schema:
    logger.info('  %-30s %s', field.name, field.type)

# %%
# Load the full DataFrame
df = pq.read_table(str(parquet_path)).to_pandas()
logger.info('Original shape: %s', df.shape)

# %%
# Quick view before transformations
logger.info(df.head())

# Descriptive statistics and missing values — baseline before preprocessing
logger.info('Missing values per column:')
null_counts = df.isna().sum()
if null_counts.sum() == 0:
    logger.info('  No missing values found — clean dataset.')
else:
    for col, n_null in null_counts[null_counts > 0].items():
        logger.info('  %-25s %d (%.2f%%)', col, n_null, 100 * n_null / len(df))

# %%
logger.info(df.describe())

# %%
# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2 — Identifier Removal
#
# RowNumber, CustomerId, Surname have no causal relation to churn.
# Removing them ensures the model learns behavior patterns,
# not spurious correlations with specific customer IDs.
# EDA Section 8.1: COLS_TO_DROP = ["RowNumber", "CustomerId", "Surname"]
# ─────────────────────────────────────────────────────────────────────────────

# %%
drop_cols = config.get('drop_columns', [])
logger.info('─' * 60)
logger.info('SECTION 2: Identifier Removal')
logger.info('Columns to drop: %s', drop_cols)

# %%
# Instantiate and apply the dropper (stateless — fit is no-op)
dropper = ColumnDropper(columns=drop_cols, logger=logger)
df = dropper.fit_transform(df)

# %%
logger.info('Shape after removal: %s', df.shape)
logger.info('Remaining columns: %s', list(df.columns))

# %%
# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3 — Missing Value Imputation  [MOVED TO THE MODELING PIPELINE]
#
# ⚠ MLOps WARNING — Data Leakage
# Imputation is STATEFUL: GroupMedianImputer learns medians/modes in fit()
# and applies them in transform(). Fitting BEFORE the train/holdout split uses
# test set information to fill NaN in the train set → data leakage.
#
# This dataset has no missing values (EDA Section 3: 0 nulls in 180,000
# cells). However, in production (real bank data) nulls are expected
# — especially in Balance (new customers) and CreditScore (no formal analysis).
#
# SOLUTION: GroupMedianImputer is applied INSIDE the modeling pipeline
# (modelagem.py), AFTER the train/holdout split.
# Strategies are configured in preprocessing.yaml → imputation.
# ─────────────────────────────────────────────────────────────────────────────

# %%
logger.info('─' * 60)
logger.info('SECTION 3: Imputation — delegated to the modeling pipeline (see modelagem.py)')
imp_specs = config.get('imputation', [])
logger.info('Configured specifications (reference): %d columns', len(imp_specs))
for spec in imp_specs:
    logger.info('  %-20s → strategy=%s', spec['column'], spec['strategy'])

n_null_total = int(df.isna().sum().sum())
logger.info(
    'Total NaN in current dataset: %d — %s',
    n_null_total,
    'clean dataset, imputation not necessary in this batch'
    if n_null_total == 0
    else 'NaN found — will be handled in the modeling pipeline',
)

# %%
# Usage reference — DataImputer will be instantiated in the modeling pipeline:
#
#   imp_cfg = config['imputation']
#   imputer = DataImputer(imputation_config=imp_cfg, logger=logger)
#   imputer.fit(X_train)           # learns medians/modes ONLY on train
#   X_train = imputer.transform(X_train)
#   X_test  = imputer.transform(X_test)
#
# Strategies configured (preprocessing.yaml → imputation):
imp_cfg = config.get('imputation', [])
for spec in imp_cfg:
    logger.info(
        '  %-20s → strategy=%-20s %s',
        spec['column'],
        spec['strategy'],
        f"(group={spec['group_column']})" if spec.get('group_column') else
        f"(fill={spec['fill_value']})"    if spec.get('fill_value') is not None else '',
    )

# %%
# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4 — Binary Flags
#
# Two patterns have special meaning in this dataset:
#
# 1. Balance == 0 → HasZeroBalance
#    - 36.17% of customers keep accounts with zero balance — this is not a data error,
#      it is a distinct banking usage behavior.
#    - Paradoxically, they show LOWER churn ("active" customers with zero balance
#      who keep the account open for other reasons).
#    - The flag allows the model to learn this pattern without confusing
#      zero balance with "missing data".
#
# 2. NumOfProducts >= 3 → HighRiskProducts
#    - 3 products: 82.7% churn | 4 products: 100% churn
#    - The inflection point is abrupt and highly non-linear.
#    - Without the flag, a linear model could not capture this threshold.
# ─────────────────────────────────────────────────────────────────────────────

# %%
flags_cfg = config.get('binary_flags', [])
logger.info('─' * 60)
logger.info('SECTION 4: Binary Flags')

# %%
# Instantiate and apply the flag transformer (stateless — fit is no-op)
flag_transformer = BinaryFlagTransformer(flags=flags_cfg, logger=logger)
df = flag_transformer.transform(df)

# %%
# Inspect the results
for spec in flags_cfg:
    new_col = spec['new_column']
    logger.info(
        "'%s': %d rows = 1 (%.2f%%)",
        new_col,
        int(df[new_col].sum()),
        100 * df[new_col].mean(),
    )

# %%
# Cross-check with the target — confirms the flags' predictive power
logger.info('Churn rate by HasZeroBalance:')
logger.info(df.groupby('HasZeroBalance')['Exited'].mean().round(4))

logger.info('Churn rate by HighRiskProducts:')
logger.info(df.groupby('HighRiskProducts')['Exited'].mean().round(4))

# %%
# ─────────────────────────────────────────────────────────────────────────────
# SECTION 5 — Interaction Features
#
# AgeInactivity: amplifies the disengagement signal in older customers.
#   Formula: Age × (1 − IsActiveMember)
#   Inactive, older customers show much higher churn.
#   Example: inactive 50-year-old → AgeInactivity = 50
#            active 50-year-old   → AgeInactivity = 0
#   The feature captures the combination of the two largest churn predictors.
#
# EngagementScore: composite customer engagement score (range: -1 to 3).
#   Formula: IsActiveMember + (NumOfProducts == 2) + HasCrCard − HasZeroBalance
#   Score 3: active customer with 2 products and card, with balance → lower risk
#   Score -1: inactive customer with no 2 products, no card, zero balance → higher risk
#
# ⚠ EngagementScore uses HasZeroBalance created in Section 4 — order matters.
# ─────────────────────────────────────────────────────────────────────────────

# %%
interact_cfg = config.get('interaction_features', [])
logger.info('─' * 60)
logger.info('SECTION 5: Interaction Features')

# %%
interact_transformer = InteractionFeatureTransformer(
    features_config=interact_cfg, logger=logger
)
df = interact_transformer.transform(df)

# %%
# Statistics of the new features
new_interact_cols = [spec['name'] for spec in interact_cfg]
logger.info(df[new_interact_cols].describe())

# %%
# Correlation with the target — validates predictive power
logger.info('Correlation of interaction features with Exited:')
for col in new_interact_cols:
    if col in df.columns:
        corr = df[col].corr(df['Exited'])
        logger.info('  %-20s r = %.4f', col, corr)

# %%
# ─────────────────────────────────────────────────────────────────────────────
# SECTION 6 — Ratio Features
#
# BalanceSalaryRatio: ratio between account balance and estimated salary.
#   Formula: Balance / (EstimatedSalary + 1)
#   Captures customers who concentrate wealth in the bank (high balance
#   relative to salary) — exactly those most contested by competitors.
#   EDA (Finding 7): higher-balance customers show 25% more churn.
#   +1 in the denominator: protection against division by zero.
# ─────────────────────────────────────────────────────────────────────────────

# %%
ratio_cfg = config.get('ratio_features', [])
logger.info('─' * 60)
logger.info('SECTION 6: Ratio Features')

# %%
ratio_transformer = RatioFeatureTransformer(ratios=ratio_cfg, logger=logger)
df = ratio_transformer.transform(df)

# %%
# Statistics of the new feature
new_ratio_cols = [spec['name'] for spec in ratio_cfg]
logger.info(df[new_ratio_cols].describe())

# %%
# Correlation with the target
logger.info('Correlation of ratio features with Exited:')
for col in new_ratio_cols:
    if col in df.columns:
        corr = df[col].corr(df['Exited'])
        logger.info('  %-20s r = %.4f', col, corr)

# %%
# ─────────────────────────────────────────────────────────────────────────────
# SECTION 7 — Age Bands (AgeGroup)
#
# The relationship between age and churn is strongly non-linear:
#   < 30 years : moderate churn
#   30–40 years: lower churn (stabilized, engaged customers)
#   40–50 years: rising churn (greater decision power and mobility)
#   50–60 years: churn peak (higher wealth, prime target for competitors)
#   60+ years  : churn falls (lower mobility, more established relationships)
#
# EDA: average age of churners = 44.8 years vs 37.4 for stayers
#      Cohen's d = 0.747 — medium-large effect
#
# Ordinal encoding (0–4): preserves natural order and is compact.
# Tree-based models (XGBoost, RF) work well with ordinals.
# ─────────────────────────────────────────────────────────────────────────────

# %%
age_cfg = config.get('age_group', {})
logger.info('─' * 60)
logger.info('SECTION 7: Age Bands (AgeGroup)')
logger.info('Bins  : %s', age_cfg.get('bins'))
logger.info('Labels: %s', age_cfg.get('labels'))

# %%
age_transformer = AgeBinTransformer(age_config=age_cfg, logger=logger)
df = age_transformer.transform(df)

# %%
# Distribution by age band
age_col = age_cfg.get('new_column', 'AgeGroup')
logger.info('AgeGroup distribution (ordinal):')
logger.info(df[age_col].value_counts().sort_index())

# %%
# Churn rate by age band — validates the pattern identified in the EDA
logger.info('Churn rate by AgeGroup:')
logger.info(df.groupby(age_col)['Exited'].agg(['mean', 'count']).round(4))

# %%
# ─────────────────────────────────────────────────────────────────────────────
# SECTION 8 — Categorical Encoding
#
# Geography (3 categories without order) → One-Hot: geo_France, geo_Germany, geo_Spain
#   EDA: Germany has churn 2× higher than France/Spain (Cramér's V=0.17, p<0.0001)
#   OHE keeps each country as an independent predictor — without assuming order.
#
# Gender (2 categories) → Binary: Gender_encoded (Male=0, Female=1)
#   EDA: females have 25.1% churn vs 16.5% for males (Cramér's V=0.11)
#   Binary encoding is compact for variables with 2 categories.
#
# Card Type (4 categories) → One-Hot: card_DIAMOND, card_GOLD, card_PLATINUM, card_SILVER
#   EDA: χ² p=0.168, Cramér's V=0.02 — no significant linear association.
#   Kept: XGBoost/RF can extract interactions via feature combinations.
# ─────────────────────────────────────────────────────────────────────────────

# %%
enc_cfg = config.get('categorical_encoding', [])
logger.info('─' * 60)
logger.info('SECTION 8: Categorical Encoding')
for spec in enc_cfg:
    logger.info('  %-12s → method=%s', spec['column'], spec['method'])

# %%
encoder = CategoricalEncoder(encoding_config=enc_cfg, logger=logger)
df = encoder.transform(df)

# %%
# Verify the OHE columns created for Geography
logger.info('Geography OHE columns:')
geo_cols = [c for c in df.columns if c.startswith('geo_')]
logger.info('  %s', geo_cols)
logger.info(df[geo_cols].sum())

# %%
# Verify binary encoding for Gender
logger.info('Binary encoding of Gender:')
if 'Gender_encoded' in df.columns:
    logger.info(df['Gender_encoded'].value_counts())
    # Validate churn rate by gender (should replicate EDA: Female > Male)
    logger.info('Churn rate by Gender_encoded (0=Male, 1=Female):')
    logger.info(df.groupby('Gender_encoded')['Exited'].mean().round(4))

# %%
# Verify the OHE columns created for Card Type
logger.info('Card Type OHE columns:')
card_cols = [c for c in df.columns if c.startswith('card_')]
logger.info('  %s', card_cols)
logger.info(df[card_cols].sum())

# %%
# ─────────────────────────────────────────────────────────────────────────────
# SECTION 9 — Feature Selection
#
# After the transformations, the DataFrame has 30+ columns.
# We need to select the subset recommended by the EDA Report:
#
#   ✓ Original numeric features (without identifiers)
#   ✓ Original binary features (HasCrCard, IsActiveMember, Complain*)
#   ✓ Derived features (flags, interactions, ratio, age band)
#   ✓ Encoding of Geography, Gender, Card Type
#   ✗ Identifiers (already removed in Section 2)
#   ✗ Original categoricals (Geography, Gender, Card Type — replaced)
#
# * Complain included with a leakage warning — verify before using in production.
#
# FeatureSelector emits WARNING (not exception) for missing columns,
# ensuring the pipeline continues even if some previous transformation
# was skipped.
# ─────────────────────────────────────────────────────────────────────────────

# %%
sel_cfg = config.get('feature_selection', {})
features_to_keep = sel_cfg.get('features_to_keep', [])
logger.info('─' * 60)
logger.info('SECTION 9: Feature Selection')
logger.info('Shape before selection: %s', df.shape)
logger.info('Requested features: %d', len(features_to_keep))

# %%
selector = FeatureSelector(features_to_keep=features_to_keep, logger=logger)
df = selector.fit_transform(df)

# %%
logger.info('Shape after selection: %s', df.shape)
logger.info('Selected columns:')
for i, col in enumerate(df.columns, 1):
    logger.info('  %2d. %s', i, col)

# %%
logger.info(df.head())

# %%
# Final statistics of the feature dataset
logger.info('Final statistics — feature dataset:')
logger.info(df.describe())

# %%
# ─────────────────────────────────────────────────────────────────────────────
# SECTION 10 — Result Persistence
#
# Save the feature dataset in Parquet (columnar, compressed format).
# This file is the INPUT for the modeling stage (modelagem.py).
#
# The file can be:
#   • Versioned in the repository (data traceability between runs)
#   • Loaded directly by the training script
#   • Compared between runs to detect feature drift over time
# ─────────────────────────────────────────────────────────────────────────────

# %%
# Create the output directory if it doesn't exist
output_dir.mkdir(parents=True, exist_ok=True)
logger.info('─' * 60)
logger.info('SECTION 10: Persistence')
logger.info('Output directory: %s', output_dir)

# %%
# Save to Parquet
df.to_parquet(str(output_path), compression=compression, index=False)
size_mb = output_path.stat().st_size / (1024 ** 2)
logger.info('File saved: %s (%.2f MB)', output_path, size_mb)

# %%
# Post-write validation: read schema without loading the data
schema_out = pq.read_schema(str(output_path))
logger.info('Output schema (%d columns):', len(schema_out))
for field in schema_out:
    logger.info('  %-35s %s', field.name, field.type)

# %%
# Read a sample for visual confirmation
df_check = pd.read_parquet(str(output_path))
logger.info('Post-read verification — shape: %s', df_check.shape)
logger.info(df_check.head())
